name: Main

on:
  push:
  schedule:
  - cron: 59 9 1 * *

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Dump job context
      env:
        JOB_CONTEXT: ${{ toJSON(job) }}
      run: echo "$JOB_CONTEXT"
    - name: Dump steps context
      env:
        STEPS_CONTEXT: ${{ toJSON(steps) }}
      run: echo "$STEPS_CONTEXT"
    - name: Dump runner context
      env:
        RUNNER_CONTEXT: ${{ toJSON(runner) }}
      run: echo "$RUNNER_CONTEXT"
    - name: Dump strategy context
      env:
        STRATEGY_CONTEXT: ${{ toJSON(strategy) }}
      run: echo "$STRATEGY_CONTEXT"
    - name: Dump matrix context
      env:
        MATRIX_CONTEXT: ${{ toJSON(matrix) }}
      run: echo "$MATRIX_CONTEXT"
  main:
    name: Main
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2.4.0
    - uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Build requirements.txt
      run: |
        pip install \
          --no-cache-dir \
          pipenv
        pipenv lock \
            --keep-outdated \
            --requirements \
          > requirements.txt
    - name: Login to Docker Hub
      uses: docker/login-action@v1.12.0
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1.6.0
    - name: Build and push
      uses: docker/build-push-action@v2.9.0
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/ansible:latest
    - name: Build requirements.txt
      run: |
        docker run \
          --rm \
          --env HOME="${PWD}" \
          --user "$(id -u):$(id -g)" \
          --volume "${PWD}:${PWD}" \
          --workdir "${PWD}" \
          arlol/ansible:latest
        git diff --exit-code
